SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `STUDENT`;
DROP TABLE IF EXISTS `SUBJECT`;
DROP TABLE IF EXISTS `TRANS_TBL`;
SET FOREIGN_KEY_CHECKS = 1;
CREATE TABLE `STUDENT` (`ID` INT NOT NULL AUTO_INCREMENT UNIQUE,
`FIRST_NAME` VARCHAR(45) NOT NULL, `LAST_NAME` VARCHAR(45) NOT NULL,
`YEAR_LEVEL` INT(2) NOT NULL, `GENDER` VARCHAR(11) NOT NULL,
`STATUS` CHAR(1) NOT NULL, PRIMARY KEY(`ID`));

CREATE TABLE `SUBJECT` (`ID` INT NOT NULL AUTO_INCREMENT UNIQUE,
`NAME` VARCHAR(45) NOT NULL, `GRADE` INT(2) NOT NULL,
`STUDENT_ID` INT NOT NULL, 
KEY `FK_STUDENT_ID` (`STUDENT_ID`),
CONSTRAINT `FK_STUDENT_ID` FOREIGN KEY (`STUDENT_ID`)
REFERENCES `STUDENT` (`ID`));

CREATE TABLE `TRANS_TBL` (`LOWER_LIMIT` INT(2) NOT NULL,
`UPPER_LIMIT` INT(2) NOT NULL, `EQUIVALENCE` CHAR(1) NOT NULL);

-- Additional fields --
ALTER TABLE `StudentMVC`.`STUDENT` ADD COLUMN `BIRTHDAY` DATE NULL;
ALTER TABLE `StudentMVC`.`STUDENT` ADD COLUMN `CREATE_TIME` DATETIME NULL; 
ALTER TABLE `StudentMVC`.`STUDENT` ADD COLUMN `UPDATE_TIME` DATETIME NULL;

INSERT INTO `TRANS_TBL` (LOWER_LIMIT, UPPER_LIMIT, EQUIVALENCE)
VALUES (65,74,'F');
INSERT INTO `TRANS_TBL` (LOWER_LIMIT, UPPER_LIMIT, EQUIVALENCE)
VALUES (75,80,'D');
INSERT INTO `TRANS_TBL` (LOWER_LIMIT, UPPER_LIMIT, EQUIVALENCE)
VALUES (81,85,'C');
INSERT INTO `TRANS_TBL` (LOWER_LIMIT, UPPER_LIMIT, EQUIVALENCE)
VALUES (86,90,'B');
INSERT INTO `TRANS_TBL` (LOWER_LIMIT, UPPER_LIMIT, EQUIVALENCE)
VALUES (91,95,'A');
INSERT INTO `TRANS_TBL` (LOWER_LIMIT, UPPER_LIMIT, EQUIVALENCE)
VALUES (96,99,'S');
INSERT INTO `STUDENT`(FIRST_NAME, LAST_NAME, YEAR_LEVEL, GENDER, STATUS)
VALUES ('A1-TestStudent','A1-LastName',1,'MALE','Y');
INSERT INTO `STUDENT`(FIRST_NAME, LAST_NAME, YEAR_LEVEL, GENDER, STATUS)
VALUES ('A2-TestStudent','A2-LastName',2,'FEMALE','Y');
INSERT INTO `STUDENT`(FIRST_NAME, LAST_NAME, YEAR_LEVEL, GENDER, STATUS)
VALUES ('A3-TestStudent','A3-LastName',3,'MALE','Y');
INSERT INTO `STUDENT`(FIRST_NAME, LAST_NAME, YEAR_LEVEL, GENDER, STATUS)
VALUES ('A4-TestStudent','A4-LastName',4,'FEMALE','Y');
INSERT INTO `STUDENT`(FIRST_NAME, LAST_NAME, YEAR_LEVEL, GENDER, STATUS)
VALUES ('A5-TestStudent','A5-LastName',1,'MALE','Y');
INSERT INTO `STUDENT`(FIRST_NAME, LAST_NAME, YEAR_LEVEL, GENDER, STATUS)
VALUES ('B1-TestStudent','B1-LastName',1,'FEMALE','N');
INSERT INTO `STUDENT`(FIRST_NAME, LAST_NAME, YEAR_LEVEL, GENDER, STATUS)
VALUES ('B2-TestStudent','B2-LastName',2,'MALE','N');
INSERT INTO `STUDENT`(FIRST_NAME, LAST_NAME, YEAR_LEVEL, GENDER, STATUS)
VALUES ('B3-TestStudent','B3-LastName',3,'FEMALE','N');
INSERT INTO `STUDENT`(FIRST_NAME, LAST_NAME, YEAR_LEVEL, GENDER, STATUS)
VALUES ('B4-TestStudent','B4-LastName',4,'MALE','N');
INSERT INTO `STUDENT`(FIRST_NAME, LAST_NAME, YEAR_LEVEL, GENDER, STATUS)
VALUES ('B5-TestStudent','B5-LastName',1,'FEMALE','N');
INSERT INTO `STUDENT`(FIRST_NAME, LAST_NAME, YEAR_LEVEL, GENDER, STATUS)
VALUES ('C1-TestStudent','C1-LastName',1,'MALE','Y');
INSERT INTO `STUDENT`(FIRST_NAME, LAST_NAME, YEAR_LEVEL, GENDER, STATUS)
VALUES ('C2-TestStudent','C2-LastName',2,'FEMALE','Y');
INSERT INTO `STUDENT`(FIRST_NAME, LAST_NAME, YEAR_LEVEL, GENDER, STATUS)
VALUES ('C3-TestStudent','C3-LastName',3,'MALE','Y');
INSERT INTO `STUDENT`(FIRST_NAME, LAST_NAME, YEAR_LEVEL, GENDER, STATUS)
VALUES ('C4-TestStudent','C4-LastName',4,'FEMALE','Y');
INSERT INTO `STUDENT`(FIRST_NAME, LAST_NAME, YEAR_LEVEL, GENDER, STATUS)
VALUES ('C5-TestStudent','C5-LastName',1,'MALE','Y');
INSERT INTO `STUDENT`(FIRST_NAME, LAST_NAME, YEAR_LEVEL, GENDER, STATUS)
VALUES ('D1-TestStudent','D1-LastName',1,'MALE','N');
INSERT INTO `STUDENT`(FIRST_NAME, LAST_NAME, YEAR_LEVEL, GENDER, STATUS)
VALUES ('D2-TestStudent','D2-LastName',2,'FEMALE','Y');
INSERT INTO `STUDENT`(FIRST_NAME, LAST_NAME, YEAR_LEVEL, GENDER, STATUS)
VALUES ('D3-TestStudent','D3-LastName',3,'MALE','N');
INSERT INTO `STUDENT`(FIRST_NAME, LAST_NAME, YEAR_LEVEL, GENDER, STATUS)
VALUES ('D4-TestStudent','D4-LastName',4,'FEMALE','Y');
INSERT INTO `STUDENT`(FIRST_NAME, LAST_NAME, YEAR_LEVEL, GENDER, STATUS)
VALUES ('D5-TestStudent','D5-LastName',1,'MALE','N');

INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('Math',98,1);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('Science',98,1);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('English',98,1);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('Math',95,2);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('Science',95,2);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('English',95,2);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('Math',90,3);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('Science',92,3);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('English',93,3);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('Math',67,4);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('Science',74,4);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('English',78,4);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('Math',88,5);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('Science',87,5);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('English',79,5);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('Math',84,6);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('Science',80,6);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('English',83,6);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('Math',66,7);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('Science',90,7);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('English',65,7);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('Math',77,8);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('Science',87,8);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('English',79,8);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('Math',78,9);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('Science',75,9);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('English',95,9);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('Math',95,10);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('Science',94,10);
INSERT INTO `SUBJECT`(NAME, GRADE, STUDENT_ID) 
VALUES ('English',96,10);
