SELECT st.ID, st.FIRST_NAME, st.LAST_NAME, st.YEAR_LEVEL, Avg(subj.GRADE) 
FROM STUDENT st INNER JOIN SUBJECT subj ON st.ID = subj.STUDENT_ID AND st.STATUS = 'Y'
GROUP BY st.ID  HAVING Avg(subj.GRADE) >= 75 ORDER BY st. YEAR_LEVEL,
Avg(subj.GRADE) DESC; 

SELECT EQUIVALENCE FROM TRANS_TBL WHERE LOWER_LIMIT <= :ave AND UPPER_LIMIT >= :ave
